name: Hello PHP CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Construction de l'image Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Vérification de Docker Compose
        run: docker compose version

      - name: Build de l'image Docker (test local CI)
        run: docker compose build

  deploy:
    name: Déploiement sur le VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au VPS et nettoyage du dossier
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p /var/www/hello-php
            cd /var/www/hello-php
            rm -rf *
          EOF

      - name: Transfert des fichiers vers le VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "."
          target: "/var/www/hello-php"

      - name: Redémarrage du conteneur sur le VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/hello-php
            docker compose down
            docker compose up -d --build
          EOF
