name: Hello PHP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Déploiement Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connexion et déploiement sur le VPS
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p /var/www/hello-php
            cd /var/www/hello-php
            rm -rf *
          EOF

      - name: Copier les fichiers sur le VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "."
          target: "/var/www/hello-php"

      - name: Redémarrer le conteneur
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /var/www/hello-php
            docker compose down
            docker compose up -d --build
          EOF
